// swift-tools-version: 6.0

import PackageDescription
import Foundation

// tobor-kit is a sibling portfolio package, consumed by local path rather
// than by tag: the published v0.1.0 tag predates the Swift surface entirely.
// The default is the depth from a canonical monorepo checkout
// (Portfolio/Utilities/source/media-tool/macos/MediaWorkbench → Portfolio/Libs/tobor-kit);
// git worktrees sit at a different depth, so TOBOR_KIT_PATH overrides it.
let toborKitPath = ProcessInfo.processInfo.environment["TOBOR_KIT_PATH"]
    ?? "../../../../../Libs/tobor-kit"

// Where `libmedia_tool.a` lives. Derived from this manifest's own location so it is correct
// in a worktree without an override; MEDIA_TOOL_LIB_DIR wins when it is set (a debug build,
// a cross-compiled artifact, CI).
let packageDir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
let defaultRustLibDir = packageDir
    .appendingPathComponent("../../target/release")
    .standardizedFileURL
    .path
let rustLibDir = ProcessInfo.processInfo.environment["MEDIA_TOOL_LIB_DIR"] ?? defaultRustLibDir

let swiftV6: [SwiftSetting] = [.swiftLanguageMode(.v6)]

let package = Package(
    name: "MediaWorkbench",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(name: "MediaWorkbench", targets: ["MediaWorkbench"]),
        .library(name: "MediaWorkbenchKit", targets: ["MediaWorkbenchKit"]),
        .library(name: "MediaToolBridge", targets: ["MediaToolBridge"])
    ],
    dependencies: [
        .package(path: toborKitPath),
        .package(url: "https://github.com/jpsim/Yams", from: "5.0.0")
    ],
    targets: [
        // C header + modulemap emitted by uniffi-bindgen. Regenerate with `make ffi`
        // from the repo root; never hand-edit.
        .systemLibrary(name: "media_toolFFI", path: "Sources/media_toolFFI"),
        // Generated Swift bindings plus the link line for the Rust staticlib.
        // unsafeFlags are allowed here because MediaWorkbench is a root package.
        .target(
            name: "MediaToolBridge",
            dependencies: ["media_toolFFI"],
            // Swift 5 language mode: this target is machine-generated by uniffi-bindgen and
            // is not ours to make strict-concurrency clean. Everything that consumes it is
            // still Swift 6.
            swiftSettings: [.swiftLanguageMode(.v5)],
            linkerSettings: [
                // The staticlib by absolute path, not `-L … -lmedia_tool`: a cargo release
                // dir holds libmedia_tool.a *and* .dylib, and `-l` would silently prefer the
                // dylib and leave the binary needing a loader path at run time.
                .unsafeFlags(["-Xlinker", "\(rustLibDir)/libmedia_tool.a"]),
                // Pulled in by the Rust side: reqwest's macOS proxy detection.
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("CoreFoundation"),
                .linkedFramework("Security")
            ]
        ),
        .target(
            name: "MediaWorkbenchKit",
            dependencies: [
                "MediaToolBridge",
                .product(name: "ToborKitUI", package: "tobor-kit"),
                .product(name: "ToborKitCore", package: "tobor-kit"),
                .product(name: "Yams", package: "Yams")
            ],
            swiftSettings: swiftV6
        ),
        .executableTarget(
            name: "MediaWorkbench",
            dependencies: ["MediaWorkbenchKit"],
            swiftSettings: swiftV6
        ),
        .testTarget(
            name: "MediaWorkbenchKitTests",
            dependencies: ["MediaWorkbenchKit"],
            swiftSettings: swiftV6
        ),
        .testTarget(
            name: "MediaToolBridgeTests",
            dependencies: ["MediaToolBridge"],
            swiftSettings: swiftV6
        )
    ]
)
